### PR TITLE
Correct copyright statement

### PR DESCRIPTION
**Pull request by aewp2**
Correct copyright statement

### CODE REVIEW

**Comment by rgrover** [comment]
+1

**Comment by autopulated** [comment]
I think this file was inherited from project_generator, and used under license

**Comment by matthewelse** [comment]
@rgrover @aewp2 @autopulated the commit in which this code was added _was_ added in this commit: project-generator/project_generator#aabc9236, which was after my internship with ARM in 2014 finished, however in this particular case since it's 23 lines of fairly unexciting code I don't have a particular problem with this PR being merged.

**Comment by aewp2** [comment]
You're right, please reject.  Hi James!

**Pull request closed without merging**
